### ISSUE TITLE
Game crashes when rift is entered with Immersive Portals is loaded

### ISSUE THREAD

**Issue by carrotbane2** [DavidQF555/Multiverse#1] opened 2022-04-23 11:27 UTC
When I load the game with both Multiverse and Immersive Portals, and then go through a rift, the game crashes (crash report attached below). When I reload the game, I am in the new dimension.
The crash report talks about a "dimension resourcekey", which IP apparently expects to exist, but Multiverse doesn't provide it. It seems a similar issue exists between IP and RFTools Dimensions (see [here](https://github.com/qouteall/ImmersivePortalsModForForge/issues/223).
Not sure if this error is on your or the IP people's end, but here you go.

Minecraft: 1.16.5
multiverse-1.16.5-1.0.4.jar
immersive-portals-0.17-mc1.16.5-forge.jar
forge-1.16.5-36.2.20-universal.jar

Full modlist is in the crashlog.

[crash-2022-04-23_12.01.15-server.txt](https://github.com/DavidQF555/Multiverse/files/8546797/crash-2022-04-23_12.01.15-server.txt)

**Comment by DavidQF555** [comment] 2022-04-25 10:14
The issue is likely caused by the fact that both Multiverse and RFTools Dimensions generate dimensions dynamically, so Immersive Portals can't find an ID or location for the dimensions. Generating dimensions dynamically is something that is not intended for Minecraft, so I would not really say that its Immersive Portals' fault, but both Multiverse and RFTools Dimensions relies on it, so with my limited knowledge on Immersive Portals, I'm not sure there really is a good fix for this.

**Comment by carrotbane2** [comment] 2022-04-25 13:24
Okay, I told the IP people.

**Closed as completed** 2023-09-05 05:28 UTC
Labels: bug, wontfix, compatibility
