### ISSUE TITLE
crash 1.20.1 entering rift

### ISSUE THREAD

**Issue by assasinwar9** [DavidQF555/Multiverse#12] opened 2024-11-04 19:11 UTC
getting a crash on entering a rift on 1.20.1

i tend to test modpacks in singleplayer first then make a server so its a singleplayer instance

decently large modpack but i can include the crashlog so hopefully will help

https://mclo.gs/0F0JDWF

crashes same on server

https://github.com/user-attachments/files/17613854/crash-2024-11-03_20.50.48-server.txt

ps thanks for the time , effort and patience!

**Comment by DavidQF555** [comment] 2024-11-09 12:19
It seems like Watchdog is crashing the server because it's encountering a deadlock when trying to fetch the blockstates of the blocks and chunks that the rift wants to replace.

**Comment by assasinwar9** [comment] 2024-11-11 17:35
If there is any questions I can answer to help please let me know. thanks for looking into this!

**Comment by assasinwar9** [comment] 2024-11-12 17:12
can confirm latest updates fixed crash on entering rift at least in single player (so likely server as well lol)

**Comment by DavidQF555** [comment] 2024-11-13 00:36
I did fix a bit of crashing relating to rift collisions in the latest version. However, I don't think the new version fixed anything relating to deadlocking or world generation speed, so it's a bit confusing. I talked to some more experienced developers who confirmed that deadlocking in this case is a possibility, so I'm not too sure. 

However, seeing as it seems to be fixed, I'll close the issue for now. Feel free to open it up again if crashing reappears.

**Closed as completed by DavidQF555** 2024-11-13 00:36 UTC
Labels: bug

**Comment by Not-February** [comment] 2024-12-16 17:30
Ah, I see. Thanks for the quick response

**Comment by Not-February** [comment] 2024-12-16 19:37
I'm still experiencing this with Multiverse 3.0.3.

It doesn't always happen, but more often than not I can replicate it by just making new worlds and generating new rifts with the kaleidite cores. Sooner or later, the deadlock will happen.

I, too, am running a rather large modpack with a lot of customizations - which unfortunately makes it a lot harder to isolate whether it's a mod conflict or not. Please let me know if you need more information.

Here's some logs and a relevant thread dump.

[latest.log](https://github.com/user-attachments/files/18156226/latest.log)
[debug.log](https://github.com/user-attachments/files/18156223/debug.log)

[threaddump.txt](https://github.com/user-attachments/files/18156213/threaddump.txt)
